openapi: 3.1.0
x-stoplight:
  id: r1uwegvp97ws4
info:
  title: Moritania Library
  version: '1.0'
  summary: The books Mori has and Reservation to them
servers:
  - url: 'http://localhost:3000'
paths:
  /books:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  isbn:
                    type: string
                  description:
                    type: string
              examples:
                example-1:
                  value: {}
      operationId: get-books
components:
  schemas: {}
