openapi: 3.1.0
x-stoplight:
  id: r1uwegvp97ws4
info:
  title: Moritania Library
  version: '1.0'
  summary: The books Mori has and Reservation to them
servers:
  - url: 'http://localhost:3000'
paths:
  /books:
    get:
      summary: book list api
      tags:
        - books
        - index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'
      operationId: get-books
    post:
      summary: create book api
      tags:
        - books
        - index
      responses: {}
      operationId: post-books
components:
  schemas:
    book:
      title: book
      x-stoplight:
        id: mkxzs5koeizai
      x-tags:
        - book
      type: object
      properties:
        id:
          type: string
          description: primary key
        title:
          type: string
          description: book title
        isbn:
          type: string
          description: book unique code
        description:
          type: string
          description: book description
      required:
        - id
        - title
        - isbn
        - description
