openapi: 3.1.0
x-stoplight:
  id: r1uwegvp97ws4
info:
  title: Moritania Library
  version: '1.0'
  summary: The books Mori has and Reservation to them
servers:
  - url: 'http://localhost:3000'
paths:
  /books:
    get:
      summary: book list api
      tags:
        - books
        - index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  titile:
                    type: string
                    description: book title
                  isbn:
                    type: string
                    description: book unique code
                  description:
                    type: string
                    description: book description
                required:
                  - titile
                  - isbn
                  - description
      operationId: get-books
    post:
      summary: create book api
      tags:
        - books
        - index
      responses: {}
      operationId: post-books
components:
  schemas: {}
