openapi: 3.1.0
x-stoplight:
  id: r1uwegvp97ws4
info:
  title: Moritania Library
  version: '1.0'
  summary: The books Mori has and Reservation to them
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
